name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"  # 每12小时运行一次
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write  # 允许写入内容

    steps:
      - name: generate my-custom-snake-animation.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: "Gaonavak"
          outputs: |
            dist/my-custom-snake-animation.svg
            dist/my-custom-snake-animation-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push my-custom-snake-animation.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
