name: Translate Markdown Files

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 确保 Git 记录完整的提交历史

      - name: Check if .md files were changed
        id: check-md
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- "*.md" || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "MD_CHANGED=true" >> $GITHUB_ENV
            echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          else
            echo "MD_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        if: env.MD_CHANGED == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Translate changed Markdown files
        if: env.MD_CHANGED == 'true'
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}  # 将文件传递给该 Action

      - name: Commit and push changes
        if: env.MD_CHANGED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $CHANGED_FILES
          git commit -m ":memo: Automated translation of changed .md files to English"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
